events {}

http {

    # -------------------------
    # HTTP (port 80) → internal Docker traffic
    # -------------------------
    server {
        listen 80;

        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
        large_client_header_buffers 4 16k;

        proxy_set_header Host localhost:5000;
        proxy_set_header X-Forwarded-Host localhost:5000;
        proxy_set_header X-Forwarded-Port 5000;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Images (static files from API)
        location ^~ /Images/ {
            proxy_pass http://imagegallery-api:5075;
        }        

        # IDP
        location /idp/ {
            proxy_pass http://imagegallery-idp:5001/idp/;
        }

        # API
        location /api/ {
            proxy_pass http://imagegallery-api:5075/;
        }

        # Client
        location / {
            proxy_pass http://imagegallery-client:7184;
        }
    }

    # -------------------------
    # HTTPS (port 443) → browser
    # -------------------------
    server {
        listen 443 ssl;

        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
        large_client_header_buffers 4 16k;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # Forwarded headers (important for ASP.NET)
        proxy_set_header Host localhost:5000;
        proxy_set_header X-Forwarded-Host localhost:5000;
        proxy_set_header X-Forwarded-Port 5000;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Images (static files from API)
        location ^~ /Images/ {
            proxy_pass http://imagegallery-api:5075;
        }        

        # IDP
        location /idp/ {
            proxy_pass http://imagegallery-idp:5001/idp/;
        }

        # API
        location /api/ {
            proxy_pass http://imagegallery-api:5075/;
        }

        # Client
        location / {
            proxy_pass http://imagegallery-client:7184;
        }
    }
}